### ISSUE TITLE
Question alignment of IHC images from 1 section

### ISSUE THREAD

**Issue by kaizen89** [MarkZaidi/QuPath-Image-Alignment#2]
Hi Mark,
I have a quick question. I have dozens of tumor sections, each section was stained separately with a marker (IHC). The whole slide images are either in .ndpi or .tif. Now, I would like to align all the images of each section and get a single file with each marker in a separate channel. Do you think your scripts can be applied to this task? Thanks a lot

**Comment by MarkZaidi** [comment]
Hey Kaizen89,

This would work for your situation. In apply-transforms.groovy, if you set `performDeconvolution` to true, it will separate the IHC stain (presumably DAB) based on the color vectors set in the image, So for each of the 12 sections, you'll get their hematoxylin stain, IHC stain, and residual (unused). If you set it to false, it will not perform stain deconvolution, and you'll have the original red, green, and blue channels for each. 

Just a fair warning, images with stain deconvolution are fairly large, as they're usually stored in single or double precision. So 3x12(dozen) sections will result in a massive 36 channel OME-tiff, which may lead to issues loading the whole image into memory if you don't have sufficient ram.

**Comment by kaizen89** [comment]
Would it work if I crop the images and save as ome.tif? I tried this just for testing, I was able to run the calculate transform. I have two stains, I checked that the second stain has a file saved ine Affine folder. However when I run the apply transform  on the refstain it throws an error `ROR: NullPointerException at line 42: Cannot invoke method readImageData() on null object`. Maybe I missed something here, anything to do between the two steps calulcate and apply transform?

Regarding the size of the final image, maybe one way to reduce size is to keep only 1 hematoxylin, and all the IHC stains. 
Thanks for your help !

**Comment by MarkZaidi** [comment]
Hmm, I've never tried using .ome.tiffs as input images, but I don't see why that wouldn't work. When you run `apply transform`, are you only running it on the reference image? Should error if you run it on other images in the project. Also, in the QuPath project, is the slideID and stain separated by an `_` ? You're on the right track, but hard to debug from that error message (especially since line 42 of the apply-transforms code on the github is some instructional commenting.

Can you share the QuPath project and images you used?

Regarding the size: Yes, that's possible. It's hard to do it in Qupath, unless you can find a way to modify the script to selectively write out specific channels. What I'd do is write out the full 36-channel image, but modify it in an external programming platform (like Python via tifffile library) to remove channels that aren't of interest.

Also, aligning and appending whole images may not even be necessary. If you're looking to see how different markers are expressed across a specific region consistent across all 12 sections, all you'd need to do is transfer the annotation across all 12 of your images, as done in https://forum.image.sc/t/qupath-multiple-image-alignment-and-object-transfer/35521 . Since each serial section effectively samples a new population of cells, measuring marker intensity in cells using a segmentation derived from one section's hematoxylin stain is likely not transferrable to the other serial sections.

**Comment by kaizen89** [comment]
Here's the link for 2 small dataset. https://drive.google.com/drive/folders/1IHFdbl3cfhU0KogorQYNeIV4v69aAZa_?usp=sharing
There are 2 folders, crop which contains 3 ome.tif files and WSI contains 3 ndpi whole slide images. I have not been able to run the 1st script on the WSI but I did on the crop one. Your assistance is much appreciated

**Comment by MarkZaidi** [comment]
No problem. Rather than just going back and forth trying to debug the error, I've attempted the alignment myself. You can watch the video here to know why it was giving an error: https://www.youtube.com/watch?v=eCBf_TJQTbY

In short, once you've loaded the .ome.tif into QuPath, rename the images in QuPath from `.ome.tif` to '.tif'. The two dots in the file name were throwing the error as it was trying to separate the image name from file extension. Also set the AutoAlignPixelSize  in `calculate transforms` to as close to 1 as you can get (better quality alignment). I was able to get it working with 10 in the video. Might take a few hours for Youtube to upload the full resolution video
